import React from 'react';
import { Sparkles, Loader2, Download } from 'lucide-react';

interface DiagramRendererProps {
  svgContent: string;
  loading?: boolean;
}

export const DiagramRenderer: React.FC<DiagramRendererProps> = ({ svgContent, loading }) => {

  const handleDownload = () => {
    if (!svgContent) return;

    // 1. Color Inversion Strategy (Dark Mode -> Paper Mode)
    // We replace the specific light colors used in renderer.ts with dark ones for the print version.
    const printSvgContent = svgContent
      .replaceAll('#f8fafc', '#000000') // Fermion White -> Black
      .replaceAll('#94a3b8', '#000000') // Text Slate -> Black
      .replaceAll('#3b82f6', '#0056b3') // Photon Light Blue -> Darker Blue (Better contrast)
      .replaceAll('#10b981', '#047857'); // Weak Green -> Darker Green

    // 2. Create Image from modified SVG
    const img = new Image();
    const svgBlob = new Blob([printSvgContent], { type: 'image/svg+xml;charset=utf-8' });
    const url = URL.createObjectURL(svgBlob);

    img.onload = () => {
      const canvas = document.createElement('canvas');
      // Set high resolution for print quality
      canvas.width = 1600; 
      canvas.height = 1000;
      const ctx = canvas.getContext('2d');

      if (ctx) {
        // 3. Draw White Background (Paper)
        ctx.fillStyle = '#ffffff'; 
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        
        // 4. Draw the SVG
        ctx.drawImage(img, 0, 0, canvas.width, canvas.height);

        // 5. Add a small footer/watermark (Optional, looks pro)
        ctx.fillStyle = '#666666';
        ctx.font = '20px monospace';
        ctx.textAlign = 'right';
        ctx.fillText('Generated by Gemini Physics', canvas.width - 30, canvas.height - 30);

        // 6. Trigger Download
        const pngUrl = canvas.toDataURL('image/png');
        const downloadLink = document.createElement('a');
        downloadLink.href = pngUrl;
        downloadLink.download = `feynman_diagram_print_${Date.now()}.png`;
        document.body.appendChild(downloadLink);
        downloadLink.click();
        document.body.removeChild(downloadLink);
        
        URL.revokeObjectURL(url);
      }
    };

    img.src = url;
  };

  return (
    <div className="relative w-full h-full min-h-[400px] flex items-center justify-center bg-slate-950/50 rounded-xl border border-slate-800/50 overflow-hidden group">
      
      {/* 1. Sci-Fi Background Grid */}
      <div className="absolute inset-0 pointer-events-none opacity-20" 
           style={{ 
             backgroundImage: 'radial-gradient(#3b82f6 1px, transparent 1px)', 
             backgroundSize: '24px 24px' 
           }}>
      </div>

      {/* 2. Loading State */}
      {loading && (
        <div className="absolute inset-0 flex flex-col items-center justify-center bg-slate-950/80 z-20 backdrop-blur-sm gap-4">
          <Loader2 className="w-10 h-10 text-cyan-400 animate-spin" />
          <div className="flex flex-col items-center">
            <span className="text-cyan-300 font-mono text-xs uppercase tracking-widest animate-pulse">Calculating Path Integrals...</span>
            <span className="text-slate-500 text-[10px] font-mono mt-1">Generating Vector Geometry</span>
          </div>
        </div>
      )}

      {/* 3. SVG Output Container */}
      <div className="relative z-10 w-full h-full p-6 flex items-center justify-center">
        {svgContent ? (
          <div 
            className="w-full h-full flex items-center justify-center transition-transform duration-700 ease-out group-hover:scale-[1.02] [&>svg]:w-full [&>svg]:h-auto [&>svg]:max-h-full [&>svg]:drop-shadow-[0_0_15px_rgba(59,130,246,0.3)]"
            dangerouslySetInnerHTML={{ __html: svgContent }} 
          />
        ) : !loading && (
          // 4. Idle State (Empty Monitor)
          <div className="flex flex-col items-center justify-center gap-3 text-slate-700 opacity-60">
            <div className="w-16 h-16 rounded-full border-2 border-slate-800 border-dashed flex items-center justify-center animate-[spin_10s_linear_infinite]">
                <div className="w-2 h-2 bg-slate-600 rounded-full" />
            </div>
            <span className="text-xs font-mono uppercase tracking-widest">Awaiting Quantum Event</span>
          </div>
        )}
      </div>
      
      {/* 5. UI Overlays */}
      {svgContent && (
        <>
          {/* Download Button (Top Right) - Only visible on hover */}
          <button 
            onClick={handleDownload}
            className="absolute top-4 right-4 p-2 bg-slate-800/90 hover:bg-cyan-900/50 text-slate-400 hover:text-cyan-200 rounded-lg backdrop-blur-md border border-slate-700 hover:border-cyan-500/50 transition-all duration-200 opacity-0 group-hover:opacity-100 translate-y-[-10px] group-hover:translate-y-0 z-20"
            title="Download as png"
          >
            <Download className="w-5 h-5" />
          </button>

          {/* Watermark (Bottom Right) */}
          <div className="absolute bottom-3 right-4 flex items-center gap-1.5 opacity-0 group-hover:opacity-100 transition-opacity duration-500 pointer-events-none">
             <Sparkles className="w-3 h-3 text-cyan-500" />
             <span className="text-[10px] font-mono text-cyan-500/60 uppercase">Gemini Physics Engine</span>
          </div>
        </>
      )}
    </div>
  );
};